import { createElement } from 'lwc';
import Esa_LC_getApprovalHistory from 'c/esa_LC_getApprovalHistory';

describe('c-esa-l-c-get-approval-history', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-esa-l-c-get-approval-history', {
            is: Esa_LC_getApprovalHistory
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});