@isTest
public with sharing class EmpiTest {
    @isTest
    static void test_plain_apex_object_construction() {
        new Empi.COCT_MT090100_LicensedEntity();
        new Empi.HCIM_IN_FindCandidatesResponse_LanguageCommunication();
        new Empi.HCIM_IN_GetDemographicsResponse_QUQI_MT120001_ControlActProcess();
        new Empi.PQ();
        new Empi.GLIST_PQ();
        new Empi.HCIM_IN_GetDemographicsResponse();
        new Empi.country_element();
        new Empi.SXCM_PPD_PQ();
        new Empi.HCIM_IN_GetRelatedIdentifiers_QUQI_MT020001_QueryByParameter();
        new Empi.SXCM_PQ();
        new Empi.RTO_MO_PQ();
        new Empi.HCIM_IN_FindCandidatesResponse_QUQI_MT120001_ControlActProcess();
        new Empi.HCIM_IN_GetRelatedIdentifiers_IdentifiedPerson();
        new Empi.MCCI_MT000300_Agent();
        new Empi.IVL_PPD_PQ();
        new Empi.HCIM_IN_FindCandidates_Person_telecom();
        new Empi.HCIM_IN_GetRelatedIdentifiers_Entity();
        new Empi.COCT_MT150000_Person();
        new Empi.AD();
        new Empi.SLIST_PQ();
        new Empi.MCCI_MT000300_TargetMessage();
        new Empi.MCCI_MT000300_RespondTo();
        new Empi.MCCI_MT000100_LocatedEntity();
        new Empi.MCCI_MT000100_RespondTo();
        new Empi.MCAI_MT900001_DetectedIssueEvent();
        new Empi.HCIM_IN_GetRelatedIdentifiers_OtherIDs();
        new Empi.MCCI_MT000300_Receiver();
        new Empi.MCCI_MT000300_Organization();
        new Empi.ADXP();
        new Empi.BL();
        new Empi.IVXB_REAL();
        new Empi.RTO();
        new Empi.RTO_INT_PQ();
        new Empi.SC();
        new Empi.IVL_MO();
        new Empi.HCIM_IN_GetDemographicsResponse_LanguageCommunication();
        new Empi.COCT_MT090100_Member();
        new Empi.QUQI_MT020001_SortControl();
        new Empi.ST();
        new Empi.CD();
        new Empi.CE();
        new Empi.HCIM_IN_GetDemographics_QUQI_MT020001_ControlActProcess();
        new Empi.QUQI_MT020001_AuthorOrPerformer();
        new Empi.CO();
        new Empi.MCCI_MT000100_AttentionLine();
        new Empi.CR();
        new Empi.CS();
        new Empi.PQR();
        new Empi.CV();
        new Empi.MCCI_MT000100_Sender();
        new Empi.TN();
        new Empi.HCIM_IN_GetRelatedIdentifiers_QUQI_MT020001_ControlActProcess();
        new Empi.TS();
        new Empi.IVL_REAL();
        new Empi.GLIST_TS();
        new Empi.HCIM_IN_GetDemographics();
        new Empi.MCAI_MT900001_Subject();
        new Empi.COCT_MT090300_Member();
        new Empi.HCIM_IN_GetDemographicsResponse_IdentifiedPerson();
        new Empi.HCIM_MT_QueryResponse_DataEnterer();
        new Empi.IVL_INT();
        new Empi.IVL_TS();
        new Empi.COCT_MT710000_LocatedEntityPartOf();
        new Empi.HCIM_IN_FindCandidatesResponse_BirthPlace();
        new Empi.PIVL_PPD_TS();
        new Empi.postalCode_element();
        new Empi.MCCI_MT000100_Agent();
        new Empi.HCIM_IN_FindCandidatesResponse();
        new Empi.HCIM_IN_GetRelatedIdentifiers_SortControl();
        new Empi.QTY();
        new Empi.IVL_PPD_TS();
        new Empi.HCIM_IN_GetDemographics_QueryByParameterPayload();
        new Empi.HCIM_IN_GetDemographicsResponse_Entity();
        new Empi.HCIM_IN_GetDemographicsResponse_Person();
        new Empi.en_delimiter();
        new Empi.ED();
        new Empi.HCIM_IN_GetRelatedIdentifiers_Member();
        new Empi.MCCI_MT000300_Sender();
        new Empi.HCIM_IN_FindCandidatesResponse_QUQI_MT120001_Subject2();
        new Empi.EN();
        new Empi.COCT_MT090100_RoleOther();
        new Empi.MCAI_MT900001_DetectedIssueManagement();
        new Empi.HCIM_IN_GetRelatedIdentifiers_Employee();
        new Empi.COCT_MT150000_OrganizationPartOf();
        new Empi.city_element();
        new Empi.HCIM_IN_FindCandidates();
        new Empi.HCIM_IN_FindCandidatesResponse_Person();
        new Empi.MCAI_MT900001_Role();
        new Empi.HCIM_IN_FindCandidates_QueryByParameterPayload();
        new Empi.HCIM_IN_GetRelatedIdentifiers_Person_id();
        new Empi.SXCM_REAL();
        new Empi.PPD_PQ();
        new Empi.en_given();
        new Empi.COCT_MT090300_RoleOther();
        new Empi.HCIM_IN_FindCandidates_Person_name();
        new Empi.IVXB_INT();
        new Empi.MCAI_MT900001_Requires();
        new Empi.BIN();
        new Empi.HCIM_MT_QueryResponse_InformationRecipient();
        new Empi.COCT_MT070000_LocatedEntity();
        new Empi.BXIT_CD();
        new Empi.MCCI_MT000100_Device();
        new Empi.IVL_PQ();
        new Empi.COCT_MT150000_ContactParty();
        new Empi.en_family();
        new Empi.state_element();
        new Empi.COCT_MT150003_Organization();
        new Empi.COCT_MT150000_OrganizationContains();
        new Empi.SXCM_MO();
        new Empi.HCIM_IN_FindCandidates_MothersMaidenName();
        new Empi.SXCM_INT();
        new Empi.HCIM_IN_FindCandidatesResponse_Employee();
        new Empi.BXIT_IVL_PQ();
        new Empi.QUQI_MT120001_AuthorOrPerformer();
        new Empi.RTO_PQ_PQ();
        new Empi.COCT_MT090100_LanguageCommunication();
        new Empi.COCT_MT090300_LicensedEntity();
        new Empi.MCCI_MT000300_Device();
        new Empi.II();
        new Empi.MCCI_MT000300_AcknowledgementDetail();
        new Empi.MCCI_MT000300_AttentionLine();
        new Empi.HCIM_IN_GetRelatedIdentifiers_QueryByParameterPayload();
        new Empi.PIVL_TS();
        new Empi.QUQI_MT020001_DataEnterer();
        new Empi.HCIM_MT_QueryResponse_Reason();
        new Empi.HCIM_IN_GetDemographicsResponse_Citizen();
        new Empi.HCIM_IN_FindCandidatesResponse_IdentifiedPerson();
        new Empi.IVXB_PPD_TS();
        new Empi.RTO_QTY_QTY();
        new Empi.HCIM_IN_FindCandidatesResponse_OtherIDs();
        new Empi.IVXB_PQ();
        new Empi.COCT_MT090300_Group();
        new Empi.EIVL_PPD_TS();
        new Empi.MCCI_MT000100_Receiver();
        new Empi.HCIM_IN_GetDemographicsResponse_Member();
        new Empi.ENXP();
        new Empi.HCIM_IN_FindCandidates_Person_id();
        new Empi.HCIM_IN_FindCandidates_Person_addr();
        new Empi.MCAI_MT900001_SourceOf();
        new Empi.HCIM_IN_GetRelatedIdentifiers_Person();
        new Empi.HCIM_IN_FindCandidatesResponse_Citizen();
        new Empi.QUQI_MT020001_Reason();
        new Empi.QUQI_MT120001_Reason();
        new Empi.URL();
        new Empi.PPD_TS();
        new Empi.HCIM_IN_FindCandidatesResponse_Subject();
        new Empi.IVXB_MO();
        new Empi.HCIM_IN_GetDemographics_SortControl();
        new Empi.HCIM_IN_FindCandidatesResponse_Member();
        new Empi.HCIM_IN_GetRelatedIdentifiers_Citizen();
        new Empi.HCIM_MT_QueryResponse_AuthorOrPerformer();
        new Empi.MCCI_MT000100_EntityRsp();
        new Empi.COCT_MT710000_LocatedEntityHasParts();
        new Empi.MCCI_MT000100_Organization();
        new Empi.MCCI_MT000300_EntityRsp();
        new Empi.MCCI_MT000300_Place();
        new Empi.HCIM_IN_FindCandidates_Person_birthTime();
        new Empi.HCIM_IN_FindCandidates_Person_statusCode();
        new Empi.MCAI_MT900001_ActOrderRequired();
        new Empi.HCIM_IN_GetDemographics_Person_id();
        new Empi.MCCI_MT000300_LocatedEntity();
        new Empi.HCIM_IN_FindCandidates_SortControl();
        new Empi.COCT_MT090100_Person();
        new Empi.COCT_MT150003_ContactParty();
        new Empi.COCT_MT150000_Organization();
        new Empi.COCT_MT150002_Organization();
        new Empi.QUQI_MT120001_DataEnterer();
        new Empi.QUQI_MT120001_QueryAck();
        new Empi.HCIM_IN_FindCandidatesResponse_Entity();
        new Empi.HCIM_IN_GetDemographicsResponse_QUQI_MT120001_Subject2();
        new Empi.HCIM_IN_GetDemographicsResponse_Student();
        new Empi.SXCM_PPD_TS();
        new Empi.COCT_MT710000_Place();
        new Empi.HCIM_IN_GetDemographics_QUQI_MT020001_QueryByParameter();
        new Empi.SXCM_TS();
        new Empi.COCT_MT090100_AssignedPerson();
        new Empi.HXIT_PQ();
        new Empi.QUQI_MT020001_InformationRecipient();
        new Empi.HCIM_IN_FindCandidates_QUQI_MT020001_QueryByParameter();
        new Empi.RTO_INT_PPD_PQ();
        new Empi.HCIM_IN_GetRelatedIdentifiersResponse_QUQI_MT120001_ControlActProcess();
        new Empi.thumbnail();
        new Empi.MO();
        new Empi.SLIST_TS();
        new Empi.COCT_MT090100_Group();
        new Empi.HCIM_IN_GetRelatedIdentifiers_Student();
        new Empi.QUQI_MT120001_Overseer();
        new Empi.COCT_MT090300_Device();
        new Empi.COCT_MT090300_LanguageCommunication();
        new Empi.HCIM_IN_GetRelatedIdentifiersResponse();
        new Empi.SXCM_CD();
        new Empi.HCIM_IN_FindCandidates_Person_administrativeGender();
        new Empi.IVXB_PPD_PQ();
        new Empi.HCIM_IN_FindCandidatesResponse_Student();
        new Empi.REAL();
        new Empi.IVXB_TS();
        new Empi.HCIM_IN_FindCandidates_QUQI_MT020001_ControlActProcess();
        new Empi.en_prefix();
        new Empi.HCIM_IN_FindCandidates_Person_deceasedTime();
        new Empi.HCIM_MT_QueryResponse_QueryAck();
        new Empi.SXPR_TS();
        new Empi.en_suffix();
        new Empi.QUQI_MT020001_Overseer();
        new Empi.ANY_x();
        new Empi.INT_x();
        new Empi.streetAddressLine_element();
        new Empi.HCIM_IN_GetDemographicsResponse_OtherIDs();
        new Empi.HCIM_IN_FindCandidatesResponse_ObservationEvent();
        new Empi.ON_x();
        new Empi.HCIM_IN_GetDemographicsResponse_Employee();
        new Empi.COCT_MT090300_AssignedDevice();
        new Empi.MCCI_MT000100_Place();
        new Empi.QUQI_MT120001_InformationRecipient();
        new Empi.COCT_MT150003_Person();
        new Empi.HCIM_MT_QueryResponse_Overseer();
        new Empi.HCIM_IN_GetRelatedIdentifiersResponse_QUQI_MT120001_Subject2();
        new Empi.HCIM_IN_GetRelatedIdentifiers();
        new Empi.MCCI_MT000300_Acknowledgement();
        new Empi.ANY_mixed();
        new Empi.HXIT_CE();
        new Empi.COCT_MT150001_Organization();
        new Empi.HCIM_IN_GetDemographicsResponse_BirthPlace();
        new Empi.TEL();
        new Empi.EIVL_TS();
        new Empi.PN();
        new Empi.QUPA_AR101102_Port();

        system.assert(true);
    }

    @isTest
    static void test_get_demographics() {
        Test.setMock(WebServiceMock.class, new MockGetDemographicsResponse());
        
        new Empi.QUPA_AR101102_Port().HCIM_IN_GetDemographics(
            new Empi.II(),
            new Empi.TS(),
            new Empi.CS(),
            new Empi.II(),
            new Empi.CS(),
            new Empi.CS(),
            new Empi.CS(),
            new Empi.MCCI_MT000100_Receiver(),
            new Empi.MCCI_MT000100_Sender(),
            new Empi.HCIM_IN_GetDemographics_QUQI_MT020001_ControlActProcess()
        );

        system.assert(true);
    }

    @isTest
    static void test_find_candidates() {
        Test.setMock(WebServiceMock.class, new MockFindCandidates());

        new Empi.QUPA_AR101102_Port().HCIM_IN_FindCandidates(
            new Empi.II(),
            new Empi.TS(),
            new Empi.CS(),
            new Empi.II(),
            new Empi.CS(),
            new Empi.CS(),
            new Empi.CS(),
            new Empi.MCCI_MT000100_Receiver(),
            new Empi.MCCI_MT000100_Sender(),
            new Empi.HCIM_IN_FindCandidates_QUQI_MT020001_ControlActProcess()
        );

        system.assert(true);
    }

    @isTest
    static void test_get_related_identifiers() {
        Test.setMock(WebServiceMock.class, new MockGetRelatedIdentifiers());

        new Empi.QUPA_AR101102_Port().HCIM_IN_GetRelatedIdentifiers(
            new Empi.II(),
            new Empi.TS(),
            new Empi.CS(),
            new Empi.II(),
            new Empi.CS(),
            new Empi.CS(),
            new Empi.CS(),
            new Empi.MCCI_MT000100_Receiver(),
            new Empi.MCCI_MT000100_Sender(),
            new Empi.HCIM_IN_GetRelatedIdentifiers_QUQI_MT020001_ControlActProcess()
        );

        system.assert(true);
    }

    public class MockGetDemographicsResponse implements WebServiceMock {
        public void doInvoke(
            Object stub,
            Object request,
            Map<String, Object> response,
            String endpoint,
            String soapAction,
            String requestName,
            String responseNS,
            String responseName,
            String responseType) {

            Empi.HCIM_IN_GetDemographicsResponse respElement = new Empi.HCIM_IN_GetDemographicsResponse();
            response.put('response_x', respElement); 
        }
    }

    public class MockGetRelatedIdentifiers implements WebServiceMock {
        public void doInvoke(
            Object stub,
            Object request,
            Map<String, Object> response,
            String endpoint,
            String soapAction,
            String requestName,
            String responseNS,
            String responseName,
            String responseType) {

            Empi.HCIM_IN_GetRelatedIdentifiersResponse respElement = new Empi.HCIM_IN_GetRelatedIdentifiersResponse();
            response.put('response_x', respElement); 
        }
    }

    public class MockFindCandidates implements WebServiceMock {
        public void doInvoke(
            Object stub,
            Object request,
            Map<String, Object> response,
            String endpoint,
            String soapAction,
            String requestName,
            String responseNS,
            String responseName,
            String responseType) {

            Empi.HCIM_IN_FindCandidatesResponse respElement = new Empi.HCIM_IN_FindCandidatesResponse();
            response.put('response_x', respElement); 
        }
    }
}
