/**********************************************************************************************
* @Author:      Deepak 
* @Date:        23/02/2023
* @Description: The purpose of this class is to have constant values to be reffered by main class
* @Revision(s): [Date] - [Change Reference] - [Changed By] - [Description]   
***********************************************************************************************/

public class ESA_cls_constants {

    public static final String Case_Approval_Time_Unit_Week = 'Week';
    public static final String Case_Approval_Time_Unit_Month = 'Month';
    public static final String Case_Approval_Time_Unit_Days = 'Days';
}