/**********************************************************************************************
* @Author:      Deepak 
* @Date:        23/02/2023
* @Description: The purpose of this class is to have constant values to be reffered by main class
* @Revision(s): [Date] - [Change Reference] - [Changed By] - [Description]   
***********************************************************************************************/

public class ESA_cls_constants {

    public static final String CASE_APPROVAL_TIME_UNIT_WEEK = 'Weeks';
    public static final String CASE_APPROVAL_TIME_UNIT_MONTH = 'Months';
    public static final String CASE_APPROVAL_TIME_UNIT_DAYS = 'Days';
}