name: Build Check
on: [pull_request_target]

jobs:
  build-check:
    runs-on: ubuntu-latest
    env:
      SFDX_DISABLE_SOURCE_MEMBER_POLLING: true
    steps:

    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install Salesforce CLI
      run: |
        npm install sfdx-cli@stable
        node_modules/sfdx-cli/bin/run --version
        node_modules/sfdx-cli/bin/run plugins --core

    - name: Authenticate DevHub
      run: |
        echo "${SALESFORCE_JWT_SECRET_KEY}" > server.key
        node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid ${{ secrets.SALESFORCE_DEVHUB_CONSUMER_KEY }} --jwtkeyfile server.key --username ${{ secrets.SALESFORCE_DEVHUB_USERNAME}} --setdefaultdevhubusername -a devhub
      env:
        SALESFORCE_JWT_SECRET_KEY: ${{ secrets.SALESFORCE_JWT_SECRET_KEY }}
        SALESFORCE_DEVHUB_CONSUMER_KEY: ${{ secrets.SALESFORCE_DEVHUB_CONSUMER_KEY }}
        SALESFORCE_DEVHUB_USERNAME: ${{ secrets.SALESFORCE_DEVHUB_USERNAME }}

    - name: Define CI org
      run: node_modules/sfdx-cli/bin/run force:org:create -v devhub -s -f config/project-scratch-def.json -a ciorg -d 1

    - name: Deploy source
      run: node_modules/sfdx-cli/bin/run force:source:push -u ciorg

    - name: Assign permission set and set user role
      run: |
        node_modules/sfdx-cli/bin/run force:user:permset:assign -u ciorg -n SA_Administrator
        node_modules/sfdx-cli/bin/run force:apex:execute -u ciorg -f scripts/apex/set-current-user.apex
        
    - name: Run Apex test
      run: node_modules/sfdx-cli/bin/run force:apex:test:run -c -r human
    
    - name: Delete scratch org
      if: ${{ always() }}
      run: node_modules/sfdx-cli/bin/run force:org:delete -u ciorg
