name: Build Check
on: [pull_request_target]

jobs:
  build-check:
    runs-on: ubuntu-latest
    env:
      SFDX_DISABLE_SOURCE_MEMBER_POLLING: true
    steps:

    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: 'Install Salesforce CLI'
      run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
          mkdir ~/sfdx
          tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
          echo "$HOME/sfdx/bin" >> $GITHUB_PATH
          ~/sfdx/bin/sfdx version
 
    - name: Authenticate DevHub
      run: |
        echo ${{ secrets.SALESFORCE_DEVHUB_AUTH }} > sfdxurl.txt
        sfdx auth:sfdxurl:store --sfdxurlfile sfdxurl.txt --setalias devhub --setdefaultdevhubusername
    - name: Define CI org
      run: sfdx force:org:create -v devhub -s -f config/project-scratch-def.json -a ciorg -d 1

    - name: checking config list
      run: sfdx config:get apiVersion

    - name: Deploy source
      run: |
        sfdx force:source:deploy -p dev-app-pre -u ciorg
        sfdx force:source:deploy -p force-app -u ciorg
        sfdx force:source:deploy -p force-app/main/default/objects,force-app/main/default/queues -u ciorg -w 15
        sfdx force:source:deploy -p dev-app-post -u ciorg
      # sfdx force:source:push -u ciorg

    - name: Assign permission set and set user role
      run: |
        sfdx force:user:permset:assign -u ciorg -n SA_Administrator
        sfdx force:apex:execute -u ciorg -f scripts/apex/scratchorg-set-current-user.apex
        
    - name: Run Apex test
      run: sfdx force:apex:test:run -c -r human

    - name: Delete scratch org
      if: ${{ always() }}
      run: sfdx force:org:delete -u ciorg -p
