name: Create new package upgrade file

on:
  push:
    branches:
    - main
    paths:
    - 'force-app/**'

jobs:
  update-sfdx-project-file:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        ref: main
        persist-credentials: true

    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install Salesforce CLI
      run: |
        npm install sfdx-cli@stable
        node_modules/sfdx-cli/bin/run --version
        node_modules/sfdx-cli/bin/run plugins --core

    - name: Authenticate DevHub
      run: |
        echo ${{ secrets.SALESFORCE_DEVHUB_AUTH }} > sfdxurl.txt
        node_modules/sfdx-cli/bin/run auth:sfdxurl:store --sfdxurlfile sfdxurl.txt --setalias devhub --setdefaultdevhubusername

    - name: Package Upgrade
      run: node_modules/sfdx-cli/bin/run force:package:version:create -v devhub -d force-app -f config/project-scratch-def.json -x -p "Special Authority App" -w 15 -c

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        # Optional but recommended
        # Defaults to "Apply automatic changes"
        commit_message: Apply package upgrade file

        # Optional branch name where commit should be pushed to
        # Defaults to the current branch
        # branch: feature-123

        # Optional options appended to `git-commit`
        # See https://git-scm.com/docs/git-commit for a list of available options
        commit_options: '--no-verify --signoff'

        # Optional glob pattern of files which should be added to the commit
        # Defaults to all (.)
        # See the `pathspec`-documentation for git
        # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
        # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
        file_pattern: sfdx-project.json

        # Optional local file path to the repository
        # Defaults to the root of the repository
        repository: .

        # Optional commit user and author settings
        commit_user_name: Gitub Packager Bot # defaults to "GitHub Actions"
        # commit_author: Gitub Packager Bot <actions@github.com> # defaults to author of the commit that triggered the run

        # Optional tag message
        # Action will create and push a new tag to the remote repository and the defined branch
        # tagging_message: 'v1.0.0'

        # Optional options appended to `git-push`
        # See git-push documentation for details: https://git-scm.com/docs/git-push#_options
        # push_options: '--force'

        # Optional: Disable dirty check and always try to create a commit and push
        skip_dirty_check: true

        # Optional: Skip internal call to `git fetch`
        skip_fetch: true