name: Deploy to EDRDQA2
on: 
  workflow_dispatch:
      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: 'Install Salesforce CLI'
      run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz
          mkdir ~/sfdx
          tar xJf sf-linux-x64.tar.xz -C ~/sfdx --strip-components 1
          echo "$HOME/sfdx/bin" >> $GITHUB_PATH
          ~/sfdx/bin/sf version

    - name: Authenticate with Sandbox
      run: |
         echo ${{ secrets.SALESFORCE_EDRDUAT_AUTH }} > sfdxurl.txt
         sf auth:sfdxurl:store --sfdx-url-file sfdxurl.txt --alias SAT-EDRDQA2

    - name: Remove auth file
      run: rm -f ./sfdxurl.txt

    - name: Deploy Source in dev-app-pre
      run: sf project deploy start -d dev-app-pre -o SAT-EDRDQA2 -w 15 --ignore-conflicts 

    - name: Deploy metadata
      run: sf project deploy start -d force-app -o SAT-EDRDQA2 -w 15 --ignore-conflicts

    - name: Re-deploy default objects 
      run: sf project deploy start -d force-app/main/default/objects -o SAT-EDRDQA2 -w 15 --ignore-conflicts

    - name: Re-deploy default queues 
      run: sf project deploy start -d force-app/main/default/queues -o SAT-EDRDQA2 -w 15 --ignore-conflicts

    - name: Deploy source default OmniStudio-Components 
      run: sf project deploy start -d OmniStudio-Components -o SAT-EDRDQA2 -w 15 --ignore-conflicts

    - name: Deploy Source in dev-app-post
      run: sf project deploy start -d dev-app-post -o SAT-EDRDQA2 -w 15 --ignore-conflicts
