name: Deploy to EDRDUAT
on: 
  workflow_dispatch:
      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: 'Install Salesforce CLI'
      run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz
          mkdir ~/sfdx
          tar xJf sf-linux-x64.tar.xz -C ~/sfdx --strip-components 1
          echo "$HOME/sfdx/bin" >> $GITHUB_PATH
          ~/sfdx/bin/sf version

    - name: Authenticate with Sandbox
      run: |
         echo ${{ secrets.SALESFORCE_EDRDUAT_AUTH }} > sfdxurl.txt
         sfdx auth:sfdxurl:store --sfdxurlfile sfdxurl.txt --setalias SAT-EDRDUAT

    - name: Remove auth file
      run: rm -f ./sfdxurl.txt

    - name: Deploy Source in dev-app-pre
      run: sfdx force:source:deploy -p dev-app-pre -u SAT-EDRDUAT -w 15

    - name: Deploy force-app
      run: sfdx force:source:deploy -p force-app -u SAT-EDRDUAT -w 15

    - name: Deploy objects and queues metadata
      run: sfdx force:source:deploy -p force-app/main/default/objects,force-app/main/default/queues -u SAT-EDRDUAT -w 15

    - name: Deploy dev-app-post
      run: sfdx force:source:deploy -p dev-app-post -u SAT-EDRDUAT -w 15

#    - name: Deploy destructive changes
#      run: sdfx force:mdapi:deploy --postdestructivechanges destructiveChanges -u SAT-EDRDUAT -o -g -l RunLocalTests -w 15
