# Unique name for this workflow
name: Deploy To PwC-QA

# Definition when the workflow should run
on:
    push:
        branches:
            - pwc-develop
        paths:
            - 'force-app/**'

# Jobs to be executed
jobs:
    deploy-to-qa:
        runs-on: ubuntu-latest
        needs: formatting-and-linting
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: '10.x'

        - name: Install Salesforce CLI
          run: |
            npm install sfdx-cli
            node_modules/sfdx-cli/bin/run --version
            node_modules/sfdx-cli/bin/run plugins --core
          
        - name: Authenticate 
          run: |
            echo "${SALESFORCE_JWT_SECRET_KEY}" > server.key
            node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid ${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwtkeyfile server.key --username ${{ secrets.SALESFORCE_PWCQA_USERNAME}} --setdefaultdevhubusername -a pwcqa
          env:
            SALESFORCE_JWT_SECRET_KEY: ${{ secrets.SALESFORCE_JWT_SECRET_KEY }}

        - name: Deploy source
          run: node_modules/sfdx-cli/bin/run force:source:push -u pwcqa