name: Package Install BUILD
on: 
  workflow_dispatch:
    inputs:
      package:
        description: 'The ID (starts with 04t) or alias of the package version to install'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install Salesforce CLI
      run: |
        npm install sfdx-cli
        node_modules/sfdx-cli/bin/run --version
        node_modules/sfdx-cli/bin/run plugins --core
      
    - name: Authenticate with Sandbox
      run: |
        echo "${{ secrets.SALESFORCE_BUILD_AUTH }}" > sfdxurl.json
        node_modules/sfdx-cli/bin/run auth:sfdxurl:store --sfdxurlfile sfdxurl.json --setalias SAT-BUILD

    - name: Remove auth file
      run: rm -f ./sfdxurl.json

    - name: Deploy Source in dev-app-pre
      run: node_modules/sfdx-cli/bin/run force:source:deploy -p dev-app-pre -u SAT-BUILD -w 15

    - name: Install version ID
      run: node_modules/sfdx-cli/bin/run force:package:install --package "${{ github.event.inputs.package }}" -u SAT-BUILD -b 15 -w 15 --noprompt --wait 10

    - name: Deploy Source in dev-app-post
      run: node_modules/sfdx-cli/bin/run force:source:deploy -p dev-app-post -u SAT-BUILD -w 15