name: Package Install STAGING
on: 
  workflow_dispatch:
    inputs:
      package:
        description: 'The ID (starts with 04t) or alias of the package version to install'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install Salesforce CLI
      run: |
        npm install sfdx-cli
        node_modules/sfdx-cli/bin/run --version
        node_modules/sfdx-cli/bin/run plugins --core
      
    - name: Authenticate DevHub
      run: |
        echo "${{ secrets.SALESFORCE_JWT_SECRET_KEY }}" > server.key
        node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid ${{ secrets.SALESFORCE_STAGING_CONSUMER_KEY }} --jwtkeyfile server.key --username ${{ secrets.SALESFORCE_STAGING_USERNAME }} --setdefaultdevhubusername --setalias STAGING --instanceurl ${{ secrets.SALESFORCE_SANDBOX_URL }}
      env:
        SALESFORCE_JWT_SECRET_KEY: ${{ secrets.SALESFORCE_JWT_SECRET_KEY }}

    - name: Deploy Source in dev-app-pre
      run: node_modules/sfdx-cli/bin/run force:source:deploy -p dev-app-pre -u STAGING

    - name: Install version ID
      run: node_modules/sfdx-cli/bin/run force:package:install --package "${{ github.event.inputs.package }}" -u ${{ secrets.SALESFORCE_STAGING_USERNAME }} -b 15 -w 15 --noprompt --wait 10

    - name: Deploy Source in dev-app-post
      run: node_modules/sfdx-cli/bin/run force:source:deploy -p dev-app-post -u STAGING