name: Package Install QA
on: 
  workflow_dispatch:
    inputs:
      package:
        description: 'The ID (starts with 04t) or alias of the package version to install'     
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ github.ref }}
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install Salesforce CLI
      run: |
        npm install sfdx-cli
        node_modules/sfdx-cli/bin/run --version
        node_modules/sfdx-cli/bin/run plugins --core
      
    - name: Authenticate DevHub
      run: |
        echo "${SALESFORCE_JWT_SECRET_KEY}" > server.key
        node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid ${{ secrets.SALESFORCE_QA_CONSUMER_KEY }} --jwtkeyfile server.key --username ${{ secrets.SALESFORCE_QA_USERNAME }} --setdefaultdevhubusername --setalias QA --instanceurl ${{ secrets.SALESFORCE_SANDBOX_URL }}
      env:
        SALESFORCE_JWT_SECRET_KEY: ${{ secrets.SALESFORCE_JWT_SECRET_KEY }}

    - name: Install Package
      run: node_modules/sfdx-cli/bin/run force:package:install --package "${{ github.event.inputs.package }}" -u ${{ secrets.SALESFORCE_QA_USERNAME }} --noprompt --wait 10